### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by adrianSRoman** [adrianSRoman/DeepWaveTorch#2]
- [x] add `setup.py` to be able to `pip install -e .`
- [x] ~~link to colab notebook with inference examples on LOCATA, FRIDA, and DCASE 2022~~
- [x] add examples that qualitatively show that this implementation is the same as the original

**Comment by iranroman** [comment]
Maybe we should say "original" instead of "numpy" when referring to the original implementation, as it uses more libraries than just numpy. Let's make this revision throughout.

**Comment by iranroman** [comment]
[make this figure bigger](https://github.com/adrianSRoman/DeepWaveTorch/blob/ab8dd3d834821ba5cd7503b4857e342020a4dd8b/README.md?plain=1#L98)

**Comment by iranroman** [comment]
also add a "quick inference" notebook under `notebooks/inference_quickstart.ipynb`, where a user can load an arbitrary file and run inference (perhaps using Eigenmike).

**Comment by iranroman** [comment]
making the changes in #3 "work" would be sufficient to consider the first iteration of this effort "done".

**Comment by iranroman** [comment]
I have raised original DeepWave's attention to our implementation: https://github.com/imagingofthings/DeepWave/issues/1
